services:
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: node index.js
    rootDir: ./backend

  - type: web
    name: frontend
    env: static
    buildCommand: cd src && npm install && npm run build
    staticPublishPath: src/build
